[package]
name = "heim-sensors"
version = "0.1.0-alpha.1"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform sensors information"
keywords = ["heim", "system", "sensor", "temperature", "fan"]
categories = ["os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[dependencies]
heim-common = { version = "0.1.0-alpha.1", path = "../heim-common" }
cfg-if = "~0.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
