[package]
name = "examples"
version = "0.0.0"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
publish = false
autoexamples = false
autobins = false

[dev-dependencies]
heim = { path = "../heim", features = ["full"] }
smol = "~0.1"
smol-potat = "~0.2"
futures = "~0.3"
futures-timer = "~3.0"
cfg-if = "~0.1"

ptree = { version = "0.2.1", default-features = false, features = ["ansi"] }
prettytable-rs = "0.8.0"
humantime = "2.0.0"

[[example]]
name = "disk_usage"
path = "disk_usage.rs"

[[example]]
name = "free"
path = "free.rs"

[[example]]
name = "uname"
path = "uname.rs"

[[example]]
name = "top"
path = "top.rs"

[[example]]
name = "pidof"
path = "pidof.rs"

[[example]]
name = "process"
path = "process.rs"

[[example]]
name = "wait"
path = "wait.rs"

[[example]]
name = "uptime"
path = "uptime.rs"
